# Generated by Django 3.1.3 on 2022-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220319_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_content',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
